CREATE TABLE `aib_listing` (
  `site_id` int(11) DEFAULT NULL,
  `post_id` int(11) DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `building_number` text,
  `building_name` text,
  `order_in_building` tinyint(4) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `artists` varchar(255) DEFAULT NULL,
  `organization` varchar(255) DEFAULT NULL,
  `event_name` varchar(255) DEFAULT NULL,
  `primary_name` varchar(255) DEFAULT NULL,
  `primary_name_selection` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `artist_count` varchar(10) DEFAULT NULL,
  `space_name` varchar(255) DEFAULT NULL,
  `street_address` varchar(255) DEFAULT NULL,
  `room_number` varchar(255) DEFAULT NULL,
  `zip_code` varchar(255) DEFAULT NULL,
  `select_friday` tinyint(4) DEFAULT NULL,
  `select_saturday` tinyint(4) DEFAULT '1',
  `select_sunday` tinyint(4) DEFAULT '1',
  `time_friday` varchar(255) DEFAULT NULL,
  `time_saturday` varchar(255) DEFAULT '12pm-7pm',
  `time_sunday` varchar(255) DEFAULT '12pm-7pm',
  `additional_time_friday` varchar(255) DEFAULT NULL,
  `additional_time_saturday` varchar(255) DEFAULT NULL,
  `additional_time_sunday` varchar(255) DEFAULT NULL,
  `admission_free` tinyint(4) DEFAULT '1',
  `admission_price` varchar(255) DEFAULT NULL,
  `long_description` text,
  `short_description` varchar(140) DEFAULT NULL,
  `media_other` varchar(255) DEFAULT NULL,
  `payment_method` varchar(255) DEFAULT NULL,
  `payment_email` varchar(255) DEFAULT NULL,
  `payment_code` tinytext,
  `benefit_submitted` int(11) DEFAULT NULL,
  `volunteer_message` text,
  `volunteer_confirmed` int(11) DEFAULT NULL,
  `squared_up` tinyint(4) DEFAULT '0',
  `pay_or_vol` tinyint(4) DEFAULT '0',
  `main_image` int(11) DEFAULT NULL,
  `legal_agreement` tinyint(4) DEFAULT '0',
  `community_agreement` tinyint(4) DEFAULT '0',
  `referral` varchar(255) DEFAULT NULL,
  `profile_story` tinyint(4) DEFAULT NULL,
  `benefit_interest` tinyint(4) DEFAULT NULL,
  `listing_complete` int(4) DEFAULT NULL,
  `child_friendly` int(4) DEFAULT NULL,
  `outdoors` int(4) DEFAULT NULL,
  `food` int(4) DEFAULT NULL,
  `drink` int(4) DEFAULT NULL,
  `for_sale` int(4) DEFAULT NULL,
  `hablamos_espanol` int(4) DEFAULT NULL,
  `handicapped_accessible` int(4) DEFAULT NULL,
  `name1` text,
  `name2` text,
  `name3` text,
  `painting` int(11) DEFAULT NULL,
  `photography` int(11) DEFAULT NULL,
  `drawing` int(11) DEFAULT NULL,
  `sculpture` int(11) DEFAULT NULL,
  `printmaking` int(11) DEFAULT NULL,
  `installation` int(11) DEFAULT NULL,
  `book_arts` int(11) DEFAULT NULL,
  `street_art` int(11) DEFAULT NULL,
  `mixed_media` int(11) DEFAULT NULL,
  `music` int(11) DEFAULT NULL,
  `theater` int(11) DEFAULT NULL,
  `dance` int(11) DEFAULT NULL,
  `performance_art` int(11) DEFAULT NULL,
  `comedy` int(11) DEFAULT NULL,
  `industrial_design` int(11) DEFAULT NULL,
  `film` int(11) DEFAULT NULL,
  `video` int(11) DEFAULT NULL,
  `graphic_design` int(11) DEFAULT NULL,
  `fashion_clothing_jewelry` int(11) DEFAULT NULL,
  `craft_folk_arts` int(11) DEFAULT NULL,
  `technology_electronics_computers` int(11) DEFAULT NULL,
  `food_culinary_arts` int(11) DEFAULT NULL,
  `architecture` int(11) DEFAULT NULL,
  `writing_literary_arts` int(11) DEFAULT NULL,
  `discussion_forum` int(11) DEFAULT NULL,
  `workshop` int(11) DEFAULT NULL,
  `walking_tours` int(11) DEFAULT NULL,
  `other_media` int(11) DEFAULT NULL,
  `post_content_holding` longtext,
  `media_features_concat` longtext,
  `food_for_sale` int(11) DEFAULT NULL,
  `drinks_for_sale` int(11) DEFAULT NULL,
  `free_food` int(11) DEFAULT NULL,
  `free_drinks` int(11) DEFAULT NULL,
  `participatory_interactive` int(11) DEFAULT NULL,
  `works_on_paper` int(11) DEFAULT NULL,
  `new_media` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
